env:
  HOSTS: "['qemu:///system']"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/virt-manager
  tag: latest@sha256:3e4df0b8456fa460990f59d66fc6fad091e9fdcb7b9d01eec71ad79d8e8c022b
persistence:
  devkvm:
    enabled: true
    mountPath: /dev/kvm
  images:
    enabled: true
    mountPath: /var/lib/libvirt/images
  libvirt-sock:
    enabled: true
    mountPath: /var/run/libvirt/libvirt-sock
  rootfolder:
    enabled: true
    mountPath: /root
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8185
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
