apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: autobrr
version: 1.0.3
appVersion: "1.7.0"
description: The modern download automation tool for torrents.
type: application
deprecated: false
home: https://truecharts.org/docs/charts/stable/autobrr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/autobrr.png
keywords:
  - autobrr
  - torrent
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/autobrr
  - https://github.com/autobrr/autobrr
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.5.10
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
