apiVersion: v2
appVersion: "elopment"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.5.7
  - condition: redis.enabled
    name: redis
    repository: https://charts.truecharts.org
    version: 3.0.67
description: Blocky is a DNS proxy and ad-blocker for the local network written in Go
home: https://truecharts.org/docs/charts/incubator/blocky
icon: https://truecharts.org/img/hotlink-ok/chart-icons/blocky.png
keywords:
  - dns
  - blocky
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: blocky
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/blocky
  - https://0xerr0r.github.io/blocky/
  - https://github.com/0xERR0R/blocky
  - https://github.com/Mozart409/blocky-frontend
  - https://hub.docker.com/r/spx01/blocky
version: 0.0.3
annotations:
  truecharts.org/catagories: |
    - network
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
